### ISSUE TITLE
[오타제보] findOrNull

### ISSUE THREAD

**Issue by ParkJiwoon** [unluckyjung/unluckyjung.github.io#31]
## Where

블로그의 [Kotlin find vs first](https://unluckyjung.github.io/kotlin/2022/05/01/kotlin-find-vs-first/) 게시글에서 사소한 오타가 있어서 제보합니다.

[2022-04-08-kotlin-find-vs-first.md](https://github.com/unluckyjung/unluckyjung.github.io/blob/master/_posts/Kotlin/2022-04-08-kotlin-find-vs-first.md) 게시글의 105 line

## How

`findOrNull` -> `firstOrNull` 로 변경해야 할 것 같아요

예시 코드에서도 `firstOrNull` 를 사용하고 있습니다

## Assignees

@unluckyjung

**Comment by unluckyjung** [comment]
https://github.com/unluckyjung/unluckyjung.github.io/commit/c79783e6b0fa6e62389b98e4ceda07d04fb5217d

반영되었습니다. 제보 감사합니다 👍
